// <auto-generated />
namespace E_Shop.Database.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addIsChecked : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addIsChecked));
        
        string IMigrationMetadata.Id
        {
            get { return "202302191213287_addIsChecked"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
